### ISSUE TITLE
Can't add new access_token to HttpClient

### ISSUE THREAD

**Issue by huanbd** [sounj142/HLSoft.BlazorWebAssembly.Authentication.OpenIdConnect#5]
Hi @sounj142 , The first to thank you for your project. It very helpful for me.
I've got an issue when I **use signin silent** to auto get new access_token, in my component use an service to make request to an api, but I see that httpClient can't add new access_token, it still use old access_token when component initialize in the first time.
This is my code in my service
```
await _stateProvider.SetAuthorizationHeader(_httpClient);
var lst = await _httpClient.GetJsonAsync<(string, decimal)[]>("/api/Manage/api1");
```

**Comment by sounj142** [comment]
Hi huanbd,

Sorry for my late reply. I'm so lazy two recent weeks :D
I just fixed this issue, please try the newest nuget ( ver. 0.7.2 Preview 4)
